anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=002
dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES
vsftpd_log_file=/proc/1/fd/1
ftpd_banner=Welcome to FTP Server
listen=YES
pasv_enable=YES
pasv_addr_resolve=YES
seccomp_sandbox=NO
background=YES
max_clients=100
max_per_ip=0
chmod_enable=YES
# Segurança: confina cada usuário ao seu home
chroot_local_user=YES
allow_writeable_chroot=YES